apiVersion: v1
kind: Service
metadata:
  name: engrai-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: engrai-server
  ports:
    - name: gateway
      port: 8400
      targetPort: gateway
      protocol: TCP
