apiVersion: apps/v1
kind: Deployment
metadata:
  name: engrai-server
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
          resources:
            requests:
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
